<a href="https://colab.research.google.com/github/Shivamtripathi13/Machine-Learning/blob/main/save_and_load_model_using_pickle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

In [19]:
url = 'https://raw.githubusercontent.com/codebasics/py/master/ML/1_linear_reg/homeprices.csv'
df = pd.read_csv(url, error_bad_lines=False)
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [20]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [21]:
model.coef_

array([135.78767123])

In [22]:
model.intercept_

180616.43835616432

In [23]:
model.predict([[5000]])

array([859554.79452055])

In [24]:
#Save Model To a File Using Python Pickle
#pickle model = it allow you to serialize your python object into a file
import pickle 

In [25]:
with open('model_pickle','wb') as f:
    pickle.dump(model,f)

In [26]:
with open('model_pickle','rb') as f:
     mp = pickle.load(f)

In [27]:
mp.predict([[5000]])

array([859554.79452055])

In [28]:
from sklearn.externals import joblib

/usr/local/lib/python3.6/dist-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [29]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [30]:
mj = joblib.load('model_joblib')

In [31]:
mj.predict([[5000]])

array([859554.79452055])